spring:
  datasource:
    url : jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:microfinance}
    username : ${DB_USER:postgres}
    password : ${DB_PASS:postgres}
    driver-class-name : org.postgresql.Driver
    hikari:
      connection-timeout : 20000
      maximum-pool-size : 5
      idle-timeout: 30000
      max-lifetime: 200000
      minimum-idle: 2
  flyway:
    schemas: customer
    locations: classpath:db.migration
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8081
  servlet:
    context-path: "/"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
  cache:
    disabled: true
