version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: database_loanapp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microfinance
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  loan-service:
    build:
      context: ../loan
    container_name: loan-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/microfinance
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_FLYWAY_VALIDATE_MIGRATION_NAMING: false
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  customer-service:
    build:
      context: ../customer
    container_name: customer-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/microfinance
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_FLYWAY_VALIDATE_MIGRATION_NAMING: false
    depends_on:
      postgres:
        condition: service_healthy
#    command: ./gradlew clean build bootRun
    restart: on-failure

  credit-service:
    build:
      context: ../credit
    container_name: credit-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/microfinance
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_FLYWAY_VALIDATE_MIGRATION_NAMING : false
    depends_on:
      postgres:
        condition: service_healthy
#    command: ../gradlew clean build bootRun
    restart: on-failure

  kyc-service:
    build:
      context: ../verification
    container_name: kyc-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/microfinance
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_FLYWAY_VALIDATE_MIGRATION_NAMING: false
    depends_on:
      postgres:
        condition: service_healthy
#    command: ./gradlew clean build bootRun
    restart: on-failure

volumes:
  postgres-data: